/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_8 (
    input [0:0] char,
    output reg [7:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      1'h0: begin
        segs = 8'hc0;
      end
      1'h1: begin
        segs = 8'hf9;
      end
      default: begin
        segs = 8'hff;
      end
    endcase
  end
endmodule
